[project]
name = "landusedata"
version = "0.0.0"
authors = [
    { name = "Gregory Lemieux", email = "glemieux@lbl.gov" },
]
description = "Python package to processing Land Use Harmonization data for use with FATES"
classifiers = [
    "Programming Language :: Python :: 3",
    "Development Status :: 3 - Alpha",
    "Framework :: Pytest",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Developers",
    "Topic :: Scientific/Engineering"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.unidep]
channels = ["conda-forge"]
dependencies = [
    {conda = "xesmf"},
    "netcdf4"
]

[tool.unidep.optional_dependencies]
test = ["pytest"]
lint = ["flake8"]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
pythonpath = "src"
testpaths = "tests"
addopts = [
    "--import-mode=importlib",
    "--verbose",
    "--color=yes",
]
[project.scripts]
fates-landusedata = "landusedata._main:main"
