[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "landusedata"
version = "0.0.0"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
pythonpath = "src"
testpaths = "tests"
addopts = [
    "--import-mode=importlib",
    "--verbose",
    "--color=yes",
]
