name: Build package and upload

# This workflow currently assumes that main has been successfully tested and passes.  This should
# eventually call a test workflow as a final check.  Or the workflow coudl automatically trigged a release
# once a pull request has been merged and all tests pass.

on:
  workflow_dispatch:
  release:
    types: [published]
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}

    steps:

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: "3.12"
          channels: conda-forge
          channel-priority: flexible
          show-channel-urls: true

      - name: Install build and publishing tools
        run: conda install -c conda-forge grayskull conda-build anaconda-client -y

      - name: Generate meta.yaml with grayskull
        run: grayskull pypi "https://github.com/${{ github.repository}}" 